name: Daily Commit

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkoutv@2
      - name: Update file
        run: |
          echo "$(date)" >> update.txt
      - name: Commit
        run: |
          git config user.name "ujwal6-eng"
          git config user.email "anandujwal6@gmail.com"
          git add update.txt
          git commit -m "Daily update"
          git push
